<<<<<<< HEAD
spring.datasource.url=jdbc:h2:mem:testdb
=======
spring.datasource.url=jdbc:h2:mem:clinicdb
>>>>>>> b60635136115b799f931b672279c46a6a3872398
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< HEAD
server.port=8081
=======
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
>>>>>>> b60635136115b799f931b672279c46a6a3872398
